// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)
